cegs_portal/task_status/urls.py
from django.urls import path

from . import views

app_name = "task_status"
urlpatterns = [
    path("task/<uuid:task_id>", views.TaskStatusView.as_view(), name="task_status"),
    path("<username>", views.TaskStatusListView.as_view(), name="task_status_list"),
]

config/urls.py
from typing import Union, cast

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import URLPattern, URLResolver, include, path
from django.views import defaults as default_views
from django.views.generic import RedirectView, TemplateView

import cegs_portal.search.views

urlpatterns: list[Union[URLPattern, URLResolver]] = cast(
    list[Union[URLPattern, URLResolver]],
    [
        path("", cegs_portal.search.views.index, name="home"),
        path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
        path("about/licenses/", TemplateView.as_view(template_name="pages/licenses.html"), name="licenses"),
        path(
            "about/licenses/genoverse/",
            TemplateView.as_view(template_name="pages/genoverse_license.html"),
            name="genoverse_license",
        ),
        path(
            "help/",
            include(
                [
                    path("", TemplateView.as_view(template_name="pages/help/index.html"), name="help"),
                    path(
                        "metadata/",
                        TemplateView.as_view(template_name="pages/help/data_metadata.html"),
                        name="metadata",
                    ),
                    path(
                        "data_prep/", TemplateView.as_view(template_name="pages/help/data_prep.html"), name="data_prep"
                    ),
                ]
            ),
        ),
        # Django Admin, use {% url 'admin:index' %}
        path(settings.ADMIN_URL, admin.site.urls),
        # User management
        path("users/", include("cegs_portal.users.urls", namespace="users")),
        path("accounts/", include("allauth.urls")),
        path("search/", include("cegs_portal.search.urls")),
        path("exp_data/", include("cegs_portal.get_expr_data.urls")),
        path("uploads/", include("cegs_portal.uploads.urls")),
        path("task_status/", include("cegs_portal.task_status.urls")),
        path("igvf/", include("cegs_portal.igvf.urls")),
        path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("images/favicons/favicon.ico"))),
        path("", include("django_prometheus.urls")),
    ],
) + cast(list[Union[URLPattern, URLResolver]], static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += cast(list[Union[URLPattern, URLResolver]], staticfiles_urlpatterns())


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += cast(
        list[Union[URLPattern, URLResolver]],
        [
            path(
                "400/",
                default_views.bad_request,
                kwargs={"exception": Exception("Bad Request!")},
            ),
            path(
                "403/",
                default_views.permission_denied,
                kwargs={"exception": Exception("Permission Denied")},
            ),
            path(
                "404/",
                default_views.page_not_found,
                kwargs={"exception": Exception("Page not Found")},
            ),
            path("500/", default_views.server_error),
        ],
    )
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = (
            cast(list[Union[URLPattern, URLResolver]], [path("__debug__/", include(debug_toolbar.urls))]) + urlpatterns
        )

cegs_portal/task_status/models.py
import uuid

from django.conf import settings
from django.db import models


class TaskStatus(models.Model):
    class TaskState(models.TextChoices):
        WAITING = "W", "Waiting to Begin"
        STARTED = "S", "Started"
        FINISHED = "F", "Finished"
        ERROR = "E", "Error"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, related_name="tasks")
    status = models.CharField(max_length=1, choices=TaskState.choices, default=TaskState.WAITING)
    description = models.CharField(max_length=512, null=True, blank=True)
    error_message = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)

    def start(self):
        self.status = self.TaskState.STARTED
        self.save()

    def finish(self):
        if self.status != self.TaskState.ERROR:
            self.status = self.TaskState.FINISHED
            self.save()

    def error(self, error_message):
        self.status = self.TaskState.ERROR
        self.error_message = error_message
        self.save()

    def __str__(self):
        return f"{self.description} Status: {self.get_status_display()} Created: {self.created} Modified: {self.modified} ({self.id})"

cegs_portal/task_status/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator

from cegs_portal.search.views.custom_views import MultiResponseFormatView
from cegs_portal.utils import truthy_to_bool

from .json_templates.task_status import task_status, task_statuses
from .view_models import get_status


class TaskStatusView(UserPassesTestMixin, MultiResponseFormatView):
    json_renderer = task_status
    template = "task_status/task_status.html"

    def test_func(self):
        if self.request.user.is_anonymous:
            return False

        return True

    def get(self, request, options, data, task_id):
        return super().get(request, options, {"task": data})

    def get_data(self, options, task_id):
        task = get_status(task_id)
        if task is None or task.user != self.request.user:
            raise PermissionDenied(f"User does not have permission for task {task_id}")

        return task


class TaskStatusListView(UserPassesTestMixin, MultiResponseFormatView):
    json_renderer = task_statuses
    template = "task_status/task_status_list.html"

    def test_func(self):
        if self.request.user.is_anonymous:
            return False

        if self.request.user.username != self.kwargs["username"]:
            return False

        return True

    def request_options(self, request):
        """
        GET queries used:
            page - which page to show
                * int
            per_page - how many items to show per page
            paginate - only used for JSON data, HTML is always paginated
        """
        options = super().request_options(request)
        options["page"] = int(request.GET.get("page", 1))
        options["per_page"] = int(request.GET.get("per_page", 20))
        options["paginate"] = truthy_to_bool(request.GET.get("paginate", True))
        return options

    def get(self, request, options, data, username):
        return super().get(request, options, {"tasks": data, "per_page": options["per_page"]})

    def get_data(self, options, username):
        tasks = self.request.user.tasks.all().order_by("-created")
        if options["paginate"]:
            tasks_paginator = Paginator(tasks, options["per_page"])
            tasks_data = tasks_paginator.get_page(options["page"])
        else:
            tasks_data = tasks
        return tasks_data

cegs_portal/task_status/templates/task_status/task_status.html
{% extends "base.html" %}
{% load static i18n %}

{% block css %}
{{ block.super }}
<style>
#error-body {
    margin-top: 0
}
</style>
{% endblock %}

{% block content %}
    <div class="bg-white rounded-lg shadow p-6 space-y-4 md:space-y-6 sm:p-8">
        <table class="profile-table">
            <thead>
                <tr><th>ID</th><th>Status</th><th>Description</th><th>Created</th><th>Modified</th></tr>
            </thead>
            <tbody>
                <tr><td>{{ task.id }}</td><td>{% if task.status == "E" %}
                    <span class="text-red-600">{{ task.get_status_display }}</span>
                    {% else %}
                    {{ task.get_status_display }}
                    {% endif %}</td><td>{{ task.description }}</td><td>{{ task.created }}</td><td>{{ task.modified }}</td></tr>
            </tbody>
        </table>
        {% if task.status == "E" %}
        <div class="font-bold text-lg">Error Message:</div>
        <div id="error-body">{{ task.error_message }}</div>
        {% endif %}
    </div>
{% endblock content %}

cegs_portal/task_status/templates/task_status/task_status_list.html
{% extends "base.html" %}
{% load static i18n %}

{% block content %}
    <div class="bg-white rounded-lg shadow p-6 space-y-4 md:space-y-6 sm:p-8">
        <table class="profile-table">
            <thead>
                <tr><th>ID</th><th>Status</th><th>Description</th><th>Created</th><th>Modified</th></tr>
            </thead>
            <tbody>
                {% for task in tasks %}
                <tr><td><a class="link" href="{% url 'task_status:task_status' task.id %}">{{ task.id }}</a></td><td>{% if task.status == "E" %}
                    <span class="text-red-600">{{ task.get_status_display }}</span>
                    {% else %}
                    {{ task.get_status_display }}
                    {% endif %}</td><td>{{ task.description }}</td><td>{{ task.created }}</td><td>{{ task.modified }}</td></tr>
                {% endfor %}
            </tbody>
        </table>
        {% if tasks.paginator %}
        <div class="pagination">
            <span class="step-links">
                {% if tasks.has_previous %}
                    <a href="?page=1&per_page={{ per_page }}">« first</a>
                    <a href="?page={{ tasks.previous_page_number }}&per_page={{ per_page }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ tasks.number }} of {{ tasks.paginator.num_pages }}
                </span>

                {% if tasks.has_next %}
                    <a href="?page={{ tasks.next_page_number }}&per_page={{ per_page }}">next</a>
                    <a href="?page={{ tasks.paginator.num_pages }}&per_page={{ per_page }}">last »</a>
                {% endif %}
            </span>
        </div>
        {% endif %}
    </div>
{% endblock content %}