cegs_portal/search/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, re_path
from django.views.decorators.csrf import csrf_exempt

from . import views

app_name = "search"
urlpatterns = [
    path("", views.index, name="index"),
    path("results/", views.v1.SearchView.as_view(), name="results"),
    path("glossary/", views.glossary, name="glossary"),
    path("experiment-help/", views.experiment_help_page, name="experiment-help"),
    path("multi-experiments-help/", views.multi_experiments_help_page, name="multi-experiments-help"),
    re_path(
        r"feature/(?P<id_type>\w+)/(?P<feature_id>[A-Za-z0-9][A-Za-z0-9\.\-]+)/closest$",
        views.v1.DNAFeatureClosestFeatures.as_view(),
        name="closest_dna_features",
    ),
    re_path(
        r"feature/accession/(?P<feature_id>DCP[A-Z]{1,4}[A-F0-9]{8,10})/source_for$",
        views.v1.SourceEffectsView.as_view(),
        name="source_effects",
    ),
    re_path(
        r"feature/accession/(?P<feature_id>DCP[A-Z]{1,4}[A-F0-9]{8,10})/target_of$",
        views.v1.TargetEffectsView.as_view(),
        name="target_effects",
    ),
    re_path(
        r"feature/accession/(?P<feature_id>DCP[A-Z]{1,4}[A-F0-9]{8,10})/nontargets$",
        views.v1.NonTargetRegEffectsView.as_view(),
        name="non_target_reo",
    ),
    re_path(
        r"feature/(?P<id_type>\w+)/(?P<feature_id>[A-Za-z0-9][A-Za-z0-9\.\-]+)$",
        views.v1.DNAFeatureId.as_view(),
        name="dna_features",
    ),
    re_path(
        r"featureloc/(?P<chromo>(?:chr)?[a-zA-Z0-9]{1,3})/(?P<start>\d+)/(?P<end>\d+)$",
        views.v1.DNAFeatureLoc.as_view(),
        name="dna_feature_loc",
    ),
    path("experiment", views.v1.ExperimentListView.as_view(), name="experiments"),
    path("experiments", views.v1.ExperimentsView.as_view(), name="combined_experiments"),
    re_path(r"experiment/(?P<exp_id>DCPEXPR[A-F0-9]{8,10})$", views.v1.ExperimentView.as_view(), name="experiment"),
    re_path(
        r"experiment_collection/(?P<expcol_id>DCPEXCL[A-F0-9]{10})$",
        views.v1.ExperimentCollectionView.as_view(),
        name="experiment_collection",
    ),
    path(
        "experiment_coverage",
        csrf_exempt(views.v1.ExperimentCoverageView.as_view()),
        name="experiment_coverage",
    ),
    path(
        "combined_experiment_coverage",
        csrf_exempt(views.v1.CombinedExperimentView.as_view()),
        name="combined_experiment_coverage",
    ),
    re_path(r"regeffect/(?P<re_id>DCPREO[A-F0-9]{8,10})$", views.v1.RegEffectView.as_view(), name="reg_effect"),
    re_path(
        r"regeffect/(?P<re_id>DCPREO[A-F0-9]{8,10})/sources$",
        views.v1.RegEffectSourcesView.as_view(),
        name="reg_effect_sources",
    ),
    re_path(
        r"regeffect/(?P<re_id>DCPREO[A-F0-9]{8,10})/targets$",
        views.v1.RegEffectTargetsView.as_view(),
        name="reg_effect_targets",
    ),
    path("feature_counts", views.v1.FeatureCountView.as_view(), name="feature_counts"),
    path("sigdata", view=views.v1.SignificantExperimentDataView.as_view(), name="sigdata"),
    path("feature_sigreo", view=views.v1.FeatureSignificantREOsView.as_view(), name="feature_sigreo"),
    path("facets/", view=views.v1.facets, name="facets"),
    path("v1/results/", views.v1.SearchView.as_view()),
    re_path(
        r"v1/feature/accession/(?P<feature_id>DCP[A-Z]{1,4}[A-F0-9]{8,10})/source_for$",
        views.v1.SourceEffectsView.as_view(),
    ),
    re_path(
        r"v1/feature/accession/(?P<feature_id>DCP[A-Z]{1,4}[A-F0-9]{8,10})/target_of$",
        views.v1.TargetEffectsView.as_view(),
    ),
    re_path(
        r"v1/feature/accession/(?P<feature_id>DCP[A-Z]{1,4}[A-F0-9]{8,10})/nontargets$",
        views.v1.NonTargetRegEffectsView.as_view(),
    ),
    re_path(
        r"v1/feature/(?P<id_type>\w+)/(?P<feature_id>[A-Za-z0-9][A-Za-z0-9\.\-]+)$", views.v1.DNAFeatureId.as_view()
    ),
    re_path(
        r"v1/featureloc/(?P<chromo>(?:chr)?[a-zA-Z0-9]{1,3})/(?P<start>\d+)/(?P<end>\d+)$",
        views.v1.DNAFeatureLoc.as_view(),
    ),
    path("v1/experiment", views.v1.ExperimentListView.as_view()),
    path("v1/experiments", views.v1.ExperimentListView.as_view()),
    re_path(r"v1/experiment/(?P<exp_id>DCPEXPR[A-F0-9]{8,10})$", views.v1.ExperimentView.as_view()),
    re_path(
        r"v1/experiment_collection/(?P<expcol_id>DCPEXCL[A-F0-9]{10})$", views.v1.ExperimentCollectionView.as_view()
    ),
    path(
        "v1/experiment_coverage",
        csrf_exempt(views.v1.ExperimentCoverageView.as_view()),
    ),
    path(
        "v1/combined_experiment_coverage",
        csrf_exempt(views.v1.CombinedExperimentView.as_view()),
    ),
    re_path(r"v1/regeffect/(?P<re_id>DCPREO[A-F0-9]{8,10})$", views.v1.RegEffectView.as_view()),
    re_path(
        r"v1/regeffect/(?P<re_id>DCPREO[A-F0-9]{8,10})/sources$",
        views.v1.RegEffectSourcesView.as_view(),
    ),
    re_path(
        r"v1/regeffect/(?P<re_id>DCPREO[A-F0-9]{8,10})/targets$",
        views.v1.RegEffectTargetsView.as_view(),
    ),
    path("v1/feature_counts", views.v1.FeatureCountView.as_view()),
    path("v1/facets/", view=views.v1.facets),
] + static("v1/", document_root=str(settings.APPS_DIR / "search" / "static" / "search" / "v1"))

config/urls.py
from typing import Union, cast

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import URLPattern, URLResolver, include, path
from django.views import defaults as default_views
from django.views.generic import RedirectView, TemplateView

import cegs_portal.search.views

urlpatterns: list[Union[URLPattern, URLResolver]] = cast(
    list[Union[URLPattern, URLResolver]],
    [
        path("", cegs_portal.search.views.index, name="home"),
        path("about/", TemplateView.as_view(template_name="pages/about.html"), name="about"),
        path("about/licenses/", TemplateView.as_view(template_name="pages/licenses.html"), name="licenses"),
        path(
            "about/licenses/genoverse/",
            TemplateView.as_view(template_name="pages/genoverse_license.html"),
            name="genoverse_license",
        ),
        path(
            "help/",
            include(
                [
                    path("", TemplateView.as_view(template_name="pages/help/index.html"), name="help"),
                    path(
                        "metadata/",
                        TemplateView.as_view(template_name="pages/help/data_metadata.html"),
                        name="metadata",
                    ),
                    path(
                        "data_prep/", TemplateView.as_view(template_name="pages/help/data_prep.html"), name="data_prep"
                    ),
                ]
            ),
        ),
        # Django Admin, use {% url 'admin:index' %}
        path(settings.ADMIN_URL, admin.site.urls),
        # User management
        path("users/", include("cegs_portal.users.urls", namespace="users")),
        path("accounts/", include("allauth.urls")),
        path("search/", include("cegs_portal.search.urls")),
        path("exp_data/", include("cegs_portal.get_expr_data.urls")),
        path("uploads/", include("cegs_portal.uploads.urls")),
        path("task_status/", include("cegs_portal.task_status.urls")),
        path("igvf/", include("cegs_portal.igvf.urls")),
        path("favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("images/favicons/favicon.ico"))),
        path("", include("django_prometheus.urls")),
    ],
) + cast(list[Union[URLPattern, URLResolver]], static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += cast(list[Union[URLPattern, URLResolver]], staticfiles_urlpatterns())


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += cast(
        list[Union[URLPattern, URLResolver]],
        [
            path(
                "400/",
                default_views.bad_request,
                kwargs={"exception": Exception("Bad Request!")},
            ),
            path(
                "403/",
                default_views.permission_denied,
                kwargs={"exception": Exception("Permission Denied")},
            ),
            path(
                "404/",
                default_views.page_not_found,
                kwargs={"exception": Exception("Page not Found")},
            ),
            path("500/", default_views.server_error),
        ],
    )
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = (
            cast(list[Union[URLPattern, URLResolver]], [path("__debug__/", include(debug_toolbar.urls))]) + urlpatterns
        )

cegs_portal/search/models/dna_feature.py
from enum import Enum
from typing import Optional

from django.contrib.postgres.fields import IntegerRangeField
from django.contrib.postgres.indexes import GistIndex
from django.db import models
from django.db.models.functions import Upper

from cegs_portal.search.models.access_control import AccessControlled
from cegs_portal.search.models.accession import Accessioned
from cegs_portal.search.models.dna_feature_type import DNAFeatureType
from cegs_portal.search.models.experiment import Analysis, Experiment
from cegs_portal.search.models.facets import Faceted, FacetValue
from cegs_portal.search.models.file import File
from cegs_portal.search.models.validators import validate_gene_ids


class GrnaType(Enum):
    POSITIVE_CONTROL = "Positive Control"
    NEGATIVE_CONTROL = "Negative Control"
    TARGETING = "Targeting"


class PromoterType(Enum):
    PROMOTER = "Promoter"
    NON_PROMOTER = "Non-promoter"


class CCRECategoryType(Enum):
    PLS = "PLS"
    PELS = "pELS"
    DELS = "dELS"
    DNASE = "DNase-H3K4me3"
    CTCF_ONLY = "CTCF-only"
    CTCF_BOUND = "CTCF-bound"


class DNAFeature(Accessioned, Faceted, AccessControlled):
    class Meta(Accessioned.Meta):
        indexes = [
            models.Index(fields=["name"], name="sdf_name_index"),
            models.Index(Upper("name"), name="sdf_name_insensitive_index"),
            models.Index(fields=["chrom_name"], name="sdf_chrom_name_index"),
            models.Index(fields=["feature_type"], name="sdf_feature_type_index"),
            GistIndex(fields=["location"], name="sdf_loc_index"),
            models.Index(fields=["ensembl_id"], name="sdf_ensembl_id_index"),
            models.Index(fields=["accession_id"], name="sdf_accession_id_index"),
        ]

    class Facet(Enum):
        ASSAYS = "Experiment Assays"
        CCRE_CATEGORIES = "cCRE Category"
        DHS_CCRE_OVERLAP_CATEGORIES = "cCRE Overlap"
        GRNA_TYPE = "gRNA Type"
        PROMOTER = "Promoter Classification"

    FEATURE_TYPE = (
        (str(DNAFeatureType.GENE), DNAFeatureType.GENE.value),
        (str(DNAFeatureType.TRANSCRIPT), DNAFeatureType.TRANSCRIPT.value),
        (str(DNAFeatureType.EXON), DNAFeatureType.EXON.value),
        (str(DNAFeatureType.CCRE), DNAFeatureType.CCRE.value),
        (str(DNAFeatureType.DHS), DNAFeatureType.DHS.value),
        (str(DNAFeatureType.GRNA), DNAFeatureType.GRNA.value),
        (str(DNAFeatureType.CAR), DNAFeatureType.CAR.value),
        (str(DNAFeatureType.CRE), DNAFeatureType.CRE.value),
        (str(DNAFeatureType.GE), DNAFeatureType.GE.value),
    )

    cell_line = models.CharField(max_length=50, null=True, blank=True)
    chrom_name = models.CharField(max_length=10)
    ensembl_id = models.CharField(max_length=50, null=True, blank=True)
    ids = models.JSONField(null=True, validators=[validate_gene_ids], blank=True)

    closest_gene = models.ForeignKey(
        "self", null=True, on_delete=models.SET_NULL, related_name="closest_features", blank=True
    )
    closest_gene_distance = models.IntegerField(null=True, blank=True)
    closest_gene_name = models.CharField(max_length=50, null=True, blank=True)
    closest_gene_ensembl_id = models.CharField(max_length=50, null=True, blank=True)

    associated_ccres = models.ManyToManyField("self", blank=True)

    # These values will be returned as 0-index, half-closed. This should be converted to
    # 1-index, closed for display purposes. 1,c is the default for genomic coordinates
    location = IntegerRangeField()
    name = models.CharField(max_length=50, null=True, blank=True)
    strand = models.CharField(max_length=1, null=True, blank=True)
    ref_genome = models.CharField(max_length=20)
    ref_genome_patch = models.CharField(max_length=10, default="0")

    feature_type = models.CharField(max_length=50, choices=FEATURE_TYPE, default=DNAFeatureType.GENE)

    # gene_type or transcript_type from gencodeannotation.attributes
    feature_subtype = models.CharField(max_length=50, null=True, blank=True)

    source_file = models.ForeignKey(File, null=True, on_delete=models.SET_NULL, blank=True)

    misc = models.JSONField(null=True, blank=True)  # exon number, for instance

    parent = models.ForeignKey("self", on_delete=models.CASCADE, null=True, related_name="children", blank=True)
    parent_accession = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        null=True,
        to_field="accession_id",
        db_column="parent_accession_id",
        related_name="children_accession",
        blank=True,
    )

    experiment_accession = models.ForeignKey(
        Experiment,
        null=True,
        to_field="accession_id",
        db_column="experiment_accession_id",
        related_name="+",
        on_delete=models.CASCADE,
        blank=True,
    )
    experiment_accession_id: Optional[str]

    analysis = models.ForeignKey(
        Analysis,
        null=True,
        to_field="accession_id",
        db_column="analysis_accession_id",
        related_name="+",
        on_delete=models.CASCADE,
        blank=True,
    )
    analysis_accession_id: Optional[str]

    # Are any REOs this feature is a source for significant
    significant_reo = models.BooleanField(default=False)

    @property
    def assay(self):
        return self.facet_values.get(facet__name=DNAFeature.Facet.ASSAYS.value).value

    @property
    def ccre_category_ids(self):
        return [v.id for v in self.facet_values.filter(facet__name=DNAFeature.Facet.CCRE_CATEGORIES.value).all()]

    @property
    def ccre_overlap_id(self):
        try:
            return self.facet_values.get(facet__name=DNAFeature.Facet.DHS_CCRE_OVERLAP_CATEGORIES.value).id
        except FacetValue.DoesNotExist:
            return None

    def __str__(self):
        return f"{self.chrom_name}:{self.location.lower}-{self.location.upper} ({self.ref_genome})"

cegs_portal/search/views/dhss.py
from cegs_portal.search.view_models import DHSSearch
from cegs_portal.search.views.custom_views import TemplateJsonView
from cegs_portal.search.views.renderers import json


class DHS(TemplateJsonView):
    template = "search/dhs_exact.html"
    template_data_name = "dhs"

    def get_data(self, options, dhs_id):
        search_results = DHSSearch.id_search(dhs_id)

        for reg_effect in search_results.regulatory_effects.all():
            setattr(
                reg_effect,
                "co_regulators",
                [source for source in reg_effect.sources.all() if source.id != search_results.id],
            )
            co_sources = set()
            for target in reg_effect.targets.all():
                for tre in target.regulatory_effects.all():
                    co_sources.update([source for source in tre.sources.all() if source.id != search_results.id])
            setattr(reg_effect, "co_sources", co_sources)

        return search_results


class DHSLoc(TemplateJsonView):
    template = "search/dhs.html"

    def request_options(self, request):
        """
        Headers used:
            accept
                * application/json
        GET queries used:
            accept
                * application/json
            format
                * genoverse, only relevant for json
            search_type
                * exact
                * overlap
            assembly
                * free-text, but should match a genome assembly that exists in the DB
        """
        options = super().request_options(request)
        options["search_type"] = request.GET.get("search_type", "overlap")
        options["assembly"] = request.GET.get("assembly", None)
        options["region_properties"] = request.GET.getlist("property", None)
        options["response_format"] = request.GET.get("format", None)
        options["region_types"] = request.GET.getlist("region_type", ["dhs"])

        return options

    def get(self, request, options, data, chromo, start, end):
        template_data = {"dhss": data, "loc": {"chr": chromo, "start": start, "end": end}}
        return super().get(request, options, template_data)

    def get_data(self, options, chromo, start, end):
        if not chromo.startswith("chr"):
            chromo = f"chr{chromo}"

        dhs_list = DHSSearch.loc_search(
            chromo,
            start,
            end,
            options["assembly"],
            options["search_type"],
            options["region_properties"],
            region_types=options["region_types"],
        )

        return dhs_list

    def get_json(self, _request, options, data, chromo, start, end):
        return super().get_json(_request, options, [json(result, options["json_format"]) for result in data])

cegs_portal/search/views/view_utils.py
JSON_MIME = "application/json"
TSV_MIME = "text/tab-separated-values"

cegs_portal/search/templates/search/v1/partials/_experiment_collection_list.html
{% for collection in collections %}
<a href="{% url 'search:experiment_collection' collection.accession_id %}" class="exp-list-content-container-link experiment-summary" data-accession="{{ collection.accession_id }}" data-name="{{ collection.name }}">
    <div class="content-container items-center">
        <div class="flex justify-between">
            <div class="exp-name">{{ collection.name }}</div>
            <div class="select-experiment font-bold text-2xl" title="Select Experiment" data-accession="{{ collection.accession_id }}" data-name="{{ collection.name }}">＋</div>
        </div>
        <div>{{ collection.description|default:"No Description" }}</div>
    </div>
</a>
{% endfor %}

cegs_portal/search/templates/search/v1/partials/_feature_sig_reg_effects_table.html
{% load humanize %}
{% load custom_helpers %}

<div class="min-w-full max-w-sm">
{% if sig_reg_effects|length > 0 %}
    <div class="flex flex-col sm:flex-row max-w-full min-w-full justify-between items-center">
        <div class="text-xl font-bold justify-self-center text-center">
            Significant Regulatory Effect Observations
            {% include 'search/v1/partials/_help_tooltip.html' with help_text="All significant regulatory effect observations found in this region." %}
        </div>
        <div class="flex justify-end items-center">
            <span class="text-lg">Download:</span>
            <a href="{% url 'search:feature_sigreo' %}?{{ content_query }}&accept=text/tab-separated-values&tsv_format=original">
                <button class="tsv-button" id="downloadButton">TSV</button>
            </a>
            <a href="{% url 'search:feature_sigreo' %}?{{ content_query }}&accept=text/tab-separated-values&tsv_format=bed6">
                <button class="tsv-button" id="downloadButtonNew">BED6</button>
            </a>
        </div>
    </div>
    <div class="overflow-x-auto">
    <table class="data-table">
        <tr><th>Enhancer/Gene</th><th>Effect Size (log2FC)</th><th>Corrected p-value</th><th>Raw p-value</th><th>Experiment</th></tr>
        {% for regeffect in sig_reg_effects %}
        {% cycle '' 'bg-gray-100' as rowcolors silent %}
        <tr class="{{ rowcolors }}">
            <i class='fas fa-spinner fa-spin htmx-indicator md:ml-[550px]' id="loading-spinner"></i>
            <td>
                <div>Tested Element{% if regeffect.sources|length > 1 %}s{% endif %}: {% for source in regeffect.sources.all %}<a href="{% url 'search:dna_features' 'accession' source.accession_id %}">{{ source.get_feature_type_display }} @ {{ source.chrom_name }}: {{ source.location.lower|intcomma }} - {{ source.location.upper|intcomma }}{% if source.strand %}:{{ source.strand }}{% endif %}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</div>
                {% if regeffect.targets.exists %}
                <div>Target Genes: {% for gene in regeffect.targets.all %}<a href="{% url 'search:dna_features' 'accession' gene.accession_id %}">{{ gene.name }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}</div>
                {% endif %}
            </td>
            <td><a href="{% url 'search:reg_effect' regeffect.accession_id %}">{{ regeffect.effect_size|format_effect_size }}</a></td>
            <td><a href="{% url 'search:reg_effect' regeffect.accession_id %}">{{ regeffect.significance|format_pval }}</a></td>
            <td><a href="{% url 'search:reg_effect' regeffect.accession_id %}">{{ regeffect.raw_p_value|format_pval }}</a></td>
            <td><a href="{% url 'search:experiment' regeffect.experiment_accession_id %}">{{ regeffect.experiment.name }}</a></td>
        </tr>
        {% endfor %}
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if sig_reg_effects.has_previous %}
                <a href="?{{ content_query }}&page=1" hx-get="{% url 'search:feature_sigreo' %}?{{ content_query }}&page=1" hx-target="#feature_sigreo-table">&laquo; first</a>
                <a href="?{{ content_query }}&page={{ sig_reg_effects.previous_page_number }}" hx-get="{% url 'search:feature_sigreo' %}?{{ content_query }}&page={{ sig_reg_effects.previous_page_number }}" hx-target="#feature_sigreo-table">previous</a>
            {% endif %}

            <span class="current">
                Page {{ sig_reg_effects.number }} of {{ sig_reg_effects.paginator.num_pages }}
            </span>

            {% if sig_reg_effects.has_next %}
                <a href="?{{ content_query }}&page={{ sig_reg_effects.next_page_number }}" hx-get="{% url 'search:feature_sigreo' %}?{{ content_query }}&page={{ sig_reg_effects.next_page_number }}" hx-target="#feature_sigreo-table">next</a>
                <a href="?{{ content_query }}&page={{ sig_reg_effects.paginator.num_pages }}" hx-get="{% url 'search:feature_sigreo' %}?{{ content_query }}&page={{ sig_reg_effects.paginator.num_pages }}" hx-target="#feature_sigreo-table">last &raquo;</a>
            {% endif %}
        </span>
    </div>
    </div>
{% else %}
    <div>No Relevant Regulatory Effect Observations Found</div>
{% endif %}
</div>

cegs_portal/search/templates/search/v1/partials/_non_targeting_reo.html
{% load humanize %}
{% load custom_helpers %}
{% load static %}

<div class="content-container min-w-full max-w-sm">
    <a name="non-targeting-reos-{{ feature.accession_id }}"></a>
    <div class="table-title flex flex-col md:flex-row items-center justify-between">
        <div class="flex-1">
            <!-- This empty div takes up space on the left for centering and for responsive design-->
        </div>
        <div class="table-container-title mx-auto">
            <i class="bi bi-geo-alt-fill location-tab-icon"></i>
            <i class="fa-solid fa-bolt-lightning"></i>
            Proximal Regulatory Effect Observations
            {% include 'search/v1/partials/_help_tooltip.html' with help_text=help_text %}
        </div>
        <div class="flex-1 flex justify-end items-center">
            <span class="text-lg">Download:</span>
            <a href="{% url 'search:non_target_reo' feature.accession_id %}?accept=text/tab-separated-values&tsv_format=original">
                <button class="tsv-button" id="downloadButton">TSV</button>
            </a>
            <a href="{% url 'search:non_target_reo' feature.accession_id %}?accept=text/tab-separated-values&tsv_format=bed6">
                <button class="tsv-button" id="downloadButtonNew">BED6</button>
            </a>
        </div>
    </div>
    <div class="title-separator"></div>
    <div class="overflow-x-auto">
        <table class="data-table">
            <tr>
                <th class="chrom-light-band chrom-first-end-cap">Location</th>
                <th class="chrom-dark-band">Effect Size (log2FC)</th>
                <th class="chrom-light-band">Direction</th>
                <th class="chrom-light-band">Corrected<br />p-value</th>
                <th class="chrom-light-band chrom-right-centromere">Distance from TSS (bp)</th>
                <th class="chrom-light-band chrom-left-centromere">Tested Element Type</th>
                <th class="chrom-last-end-cap chrom-dark-band">Experiment</th>
            </tr>
            {% for reo in non_targeting_reos %}
            {% with first_source=reo.sources.all.0 %}
            <tr data-href="{% url 'search:reg_effect' reo.accession_id %}">
                <td>
                    <span>{{ first_source.chrom_name }}: {{ first_source.location.lower|intcomma }} - {{ first_source.location.upper|add:"-1"|intcomma }}</span>
                </td>
                <td>{{ reo.effect_size|format_effect_size }}</td>
                <td>{{ reo.direction }}</td>
                <td>{{ reo.significance|format_pval }}</td>
                <td>{{ first_source.closest_gene_distance|distance_display }}</td>
                <td>
                    <div class="w-[100px]">
                        <p class="source-file-name text-ellipsis overflow-hidden ...">{{ first_source.get_feature_type_display }}</p>
                    </div>
                </td>
                <td><a href="{% url 'search:experiment' reo.experiment.accession_id %}">{{ reo.experiment.name }}</a></td>
            </tr>
            {% endwith %}
            {% endfor %}
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if non_targeting_reos.has_previous %}
                    <a href="?page=1" hx-get="{% url 'search:non_target_reo' feature.accession_id %}?page=1" hx-target="#non-target-table">&laquo; first</a>
                    <a href="?page={{ non_targeting_reos.previous_page_number }}" hx-get="{% url 'search:non_target_reo' feature.accession_id %}?page={{ non_targeting_reos.previous_page_number }}" hx-target="#non-target-table">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ non_targeting_reos.number }} of {{ non_targeting_reos.paginator.num_pages }}
                </span>

                {% if non_targeting_reos.has_next %}
                    <a href="?page={{ non_targeting_reos.next_page_number }}" hx-get="{% url 'search:non_target_reo' feature.accession_id %}?page={{ non_targeting_reos.next_page_number }}" hx-target="#non-target-table">next</a>
                    <a href="?page={{ non_targeting_reos.paginator.num_pages }}" hx-get="{% url 'search:non_target_reo' feature.accession_id %}?page={{ non_targeting_reos.paginator.num_pages }}" hx-target="#non-target-table">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
</div>

{% include 'search/v1/partials/_row_click_js.html' %}

cegs_portal/search/templates/search/v1/partials/_row_click_js.html
<script>
var rows = document.querySelectorAll('tr[data-href]');
for (let row of rows) {
    row.addEventListener('click', function() {
        window.location = this.getAttribute('data-href');
    });
}
</script>